spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:watch.sqlite3
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com.zy7y.watch_server.dao: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zy7y.watch_server.pojo

page helper:
  helperDialect: sqlite
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
